version: '2'
services:
    ticket-app:
        image: ticket
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ticket-postgresql:5432/ticket
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ticket-postgresql:
        extends:
            file: postgresql.yml
            service: ticket-postgresql
